region                = "us-east-1"
project_name          = "chaydemo-infra"
vpc_cidr              = "10.0.0.0/16"
public_subnet_cidrs   = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs  = ["10.0.3.0/24", "10.0.4.0/24"]
availability_zones    = ["us-east-1a", "us-east-1b"]
instance_type         = "t3.micro"
asg_min_size          = 1
asg_max_size          = 3
asg_desired_capacity  = 2
db_instance_class     = "db.t3.micro"
db_allocated_storage  = 20
db_engine_version     = "15.0"
db_username           = "admin"
db_password           = "chay"
db_name               = "chaitu"
domain_name           = "app.com"
allowed_ssh_ip        = "203.0.113.1/32"
alarm_email           = "vchaitanya4545@gmail.com.com"

